#!/usr/bin/env node
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const dataFile = new URL('../../data/customs/reunion-2026.json', import.meta.url);
const target = new URL('../../supabase/migrations/20260917000005_customs_reunion_2026.sql', import.meta.url);
const bytes = fs.readFileSync(dataFile);
const dataset = JSON.parse(bytes);
const { source, records } = dataset;
assert.equal(source.id, 'reunion-2026-dcp2026-0296');
assert.equal(source.destination, '974');
assert.equal(records.length, 10790);
assert.equal(new Set(records.map(row => row.id)).size, records.length);
const literal = value => "'" + String(value).replaceAll("'", "''") + "'";
const values = records.map(row => {
  assert.equal(row.source_id, source.id); assert.equal(row.source_url, source.url);
  assert.equal(row.destination_code, source.destination); assert.match(row.code, /^\d{8}(\d{2})?$/);
  assert.ok(row.label.trim());
  for (const rate of [row.om, row.omr]) assert.ok(rate === null || (Number.isFinite(rate) && rate >= 0 && rate <= 100));
  return [row.id, row.code, row.label, row.om, row.omr, row.page, row.notes, row.conditions];
});
const tag = '$customs_reunion_2026$';
const json = '[\n' + values.map(row => JSON.stringify(row)).join(',\n') + '\n]';
assert.ok(!json.includes(tag));
const hash = createHash('sha256').update(bytes).digest('hex');
const sql = `-- Generated by scripts/customs/build-seed.mjs; do not edit extracted rates by hand.
-- Source: ${source.url}
-- Original PDF SHA256: ${source.sha256}; PDF pages ${source.firstPage}-${source.lastPage}.
-- Dataset SHA256: ${hash}
-- 2026 reference transcription, not a guarantee against subsequent amendments.
-- Import EXTERNAL OME/OMER only. Preserve exceptions, 10-digit subdivisions and NULL rates.
INSERT INTO customs_tariffs(id,code,label,om,omr,page,notes,conditions,destination_code,source_id,source_label,source_url,source_date,source_status)
SELECT r->>0,r->>1,r->>2,(r->>3)::numeric,(r->>4)::numeric,(r->>5)::integer,r->>6,r->>7,
 ${literal(source.destination)},${literal(source.id)},${literal(source.label)},${literal(source.url)},${literal(source.date)}::date,'reference'
FROM jsonb_array_elements(${tag}${json}${tag}::jsonb) r;
`;
if (process.argv.includes('--check')) assert.equal(fs.readFileSync(target, 'utf8'), sql, 'Regenerate the seed after reviewing a dataset change.');
else fs.writeFileSync(target, sql);
console.log(`${process.argv.includes('--check') ? 'Verified' : 'Generated'} ${records.length} rows, ${Buffer.byteLength(sql)} bytes: ${fileURLToPath(target)}`);
