const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const path=require('node:path');const esbuild=require('../../node_modules/esbuild');
let bundle;
async function handler(db,env={APP_URL:'https://app.example.test'}) {if(!bundle){const result=await esbuild.build({entryPoints:[path.resolve(__dirname,'../functions/create-staff-user/index.ts')],bundle:true,write:false,format:'iife',platform:'browser',plugins:[{name:'mock',setup(build){build.onResolve({filter:/^https:\/\/esm.sh\/@supabase\//},()=>({path:'supabase',namespace:'mock'}));build.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const createClient=()=>globalThis.__db;',loader:'js'}));}}]});bundle=result.outputFiles[0].text;}let serve;vm.runInNewContext(bundle,{__db:db,Deno:{env:{get:k=>env[k]},serve:fn=>serve=fn},Request,Response,URL,console:{log(){},error(){},warn(){}}});return serve;}
function database({role='directeur',failed=false}={}){const calls=[];const db={calls,auth:{getUser:async()=>({data:{user:{id:'actor',email:'direction@example.test'}}}),admin:{inviteUserByEmail:async(email,options)=>{calls.push(['invite',email,options]);return{data:{user:{id:'new-staff'}},error:null};},createUser:async()=>{throw Error('Manual password must not be used by invitation mode');},deleteUser:async id=>{calls.push(['rollback',id]);return{error:null};}}},rpc:async()=>({data:{perm_colis_preparer:true},error:null}),from(table){let mutation;const q={select(){return q;},eq(){return q;},insert(v){mutation=v;calls.push(['insert',table,v]);return q;},single:async()=>result(),then:(ok,bad)=>Promise.resolve(result()).then(ok,bad)};function result(){if(table==='profiles')return{data:{id:'actor',role,actif:true},error:null};if(table==='staff_users')return mutation&&failed?{error:{message:'Simulated staff insert failure'}}:{data:{id:'staff',actif:true},error:null};return{data:{perm_admin_utilisateurs:true},error:null};}return q;}};return db;}
const request=body=>new Request('http://localhost/test',{method:'POST',headers:{authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify(body)});
const form={nom:'Camille',prenom:'Test',email:'camille@example.test',role:'preparateur',mode:'invite'};
test('staff invitation creates no manually shared password and preserves role defaults',async()=>{const db=database();const run=await handler(db);const response=await run(request(form));assert.equal(response.status,200);const data=await response.json();assert.equal(data.invitation_sent,true);assert.equal(db.calls.filter(c=>c[0]==='invite').length,1);assert.equal(db.calls[0][2].redirectTo,'https://app.example.test/password');assert.ok(db.calls.some(c=>c[1]==='staff_permissions'));});
test('invitation is denied for delegated user-management role before email side effect',async()=>{const db=database({role:'preparateur'});const run=await handler(db);assert.equal((await run(request(form))).status,403);assert.equal(db.calls.length,0);});
test('invalid email and missing application URL fail before invitation',async()=>{let db=database();let run=await handler(db);assert.equal((await run(request({...form,email:'bad@'}))).status,400);assert.equal(db.calls.length,0);db=database();run=await handler(db,{});assert.equal((await run(request(form))).status,503);assert.equal(db.calls.length,0);});
test('failed staff provisioning removes newly invited auth account and does not claim success',async()=>{const db=database({failed:true});const run=await handler(db);const response=await run(request(form));assert.notEqual(response.status,200);assert.ok(db.calls.some(c=>c[0]==='rollback'&&c[1]==='new-staff'));});
