BEGIN;
CREATE FUNCTION mode_assert(ok boolean,label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF NOT coalesce(ok,false) THEN RAISE EXCEPTION 'FAIL: %',label;END IF;RAISE NOTICE 'PASS: %',label;END; $$;
CREATE FUNCTION mode_reject(command text,label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE command;EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'PASS rejected: %',label;RETURN;END;RAISE EXCEPTION 'FAIL accepted: %',label;END; $$;
CREATE FUNCTION mode_resource(provider text,parcel text,reference text,live boolean) RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object('id',provider,'object','payment','is_live',live,'is_paid',true,'amount',3798,'amount_refunded',0,'currency','EUR','billing',jsonb_build_object('email','buyerlegacy@example.test'),'metadata',jsonb_build_object('colis_id',parcel,'colis_ref',reference)) $$;
SELECT mode_assert(NOT has_function_privilege('authenticated','ack_legacy_test_payplug_payment(jsonb)','EXECUTE'),'Browser cannot acknowledge legacy test resources');
SELECT mode_assert(NOT has_function_privilege('anon','ack_legacy_test_payplug_payment(jsonb)','EXECUTE'),'Anonymous cannot acknowledge legacy test resources');
SELECT mode_reject($q$SELECT confirm_legacy_payplug_payment(mode_resource('pay_legacyPending','90000000-0000-4000-8000-000000000001','EXP-LEGACY',false))$q$,'Test resource cannot create a legacy receipt through original command');
SELECT mode_reject($q$SELECT ack_legacy_test_payplug_payment(mode_resource('pay_legacyPending','90000000-0000-4000-8000-000000000001','EXP-LEGACY',false))$q$,'Acknowledgement endpoint cannot credit unpaid historical test link');
SELECT mode_assert((SELECT paiement_date IS NULL AND paiement_montant IS NULL FROM colis WHERE ref='EXP-LEGACY'),'Pending test link stays unpaid');
SELECT mode_assert((SELECT count(*)=1 FROM paiements),'Test callbacks never create ledger entries');
SELECT mode_assert((SELECT points=7 FROM clients WHERE id='80000000-0000-4000-8000-000000000001'),'Test callbacks never award loyalty points');
SELECT mode_assert((ack_legacy_test_payplug_payment(mode_resource('pay_legacyPaid','90000000-0000-4000-8000-000000000002','EXP-PAID',false))->'alreadyPaid')='true'::jsonb,'Already recorded historical test payment can be acknowledged');
SELECT mode_assert((ack_legacy_test_payplug_payment(mode_resource('pay_legacyPaid','90000000-0000-4000-8000-000000000002','EXP-PAID',false))->'financialConfirmation')='false'::jsonb,'Historical test acknowledgement never certifies a live receipt');
SELECT mode_assert((SELECT count(*)=1 FROM paiements),'Repeated historical test acknowledgements create no duplicate ledger');
SELECT mode_assert((SELECT paiement_date='2026-01-01T00:00:00Z' FROM colis WHERE ref='EXP-PAID'),'Historical observation date remains unchanged');
SELECT mode_reject($q$SELECT ack_legacy_test_payplug_payment(mode_resource('pay_legacyPaid','90000000-0000-4000-8000-000000000002','EXP-PAID',true))$q$,'Test-only acknowledgement rejects a live resource');
SELECT confirm_legacy_payplug_payment(mode_resource('pay_legacyPending','90000000-0000-4000-8000-000000000001','EXP-LEGACY',true));
SELECT mode_assert((SELECT count(*)=1 FROM paiements WHERE provider_id='pay_legacyPending'),'Verified live resource can still settle the historical quote exactly once');
ROLLBACK;
