/* Synthetic client/public audit regression: every business API is intercepted. */
const {chromium}=require('playwright');
const AxeBuilder=require('@axe-core/playwright').default;
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {setup,base,ids}=require('./browser-regression.cjs');
const output=process.env.PINTA_CLIENT_SIMPLICITY_OUT||'/tmp/pinta-client-simplicity';
const results=[];
(async()=>{
 const browser=await chromium.launch({headless:true}); await fs.mkdir(output,{recursive:true});
 const open=async f=>{await f.login();await f.page.goto(`${base}/colis/${ids.P}`);await f.page.getByRole('region',{name:'État actuel et prochaine étape',exact:true}).waitFor();};
 async function check(name,run){const f=await setup(browser,'client');f.page.setDefaultTimeout(10000);try{await run(f);assert.deepEqual(f.errors,[]);assert.deepEqual(f.networkDenied,[]);assert.equal(f.requests.some(r=>r.path.endsWith('/queue_message')),false);results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});process.exitCode=1;await f.page.screenshot({path:path.join(output,`${name}-failure.png`),fullPage:true}).catch(()=>{});}finally{await f.context.close();}}
 try{
 await check('auth-recovery-and-account-mode',async f=>{
  await f.page.goto(`${base}/password#error=access_denied&error_code=otp_expired`);await f.page.getByRole('alert').filter({hasText:'n’est plus valable'}).waitFor();
  await f.page.getByLabel('Email',{exact:true}).fill('audit@example.test');await f.page.getByRole('button',{name:'Envoyer le lien de réinitialisation',exact:true}).click();await f.page.getByRole('status').filter({hasText:'Vérifiez votre messagerie'}).waitFor();assert.equal(f.requests.filter(r=>r.path.includes('/recover')).length,1);
  await f.page.getByText('Première connexion ?',{exact:true}).click();await f.page.getByRole('link',{name:'Demander mon accès à l’équipe'}).waitFor();
  await f.login();await f.page.goto(`${base}/password`);await f.page.getByRole('heading',{name:'Modifier mon mot de passe',exact:true}).waitFor();await f.page.getByText('audit@example.test',{exact:true}).waitFor();
 });
 await check('empty-first-step-and-archive-search',async f=>{
  f.tables.colis=[{...f.tables.colis[0],id:'83333333-3333-4333-8333-333333333333',ref:'EXP-HISTORY',archive:true,statut:'livre'}];f.tables.factures=[];f.tables.lignes=[];
  await f.login();await f.page.getByRole('heading',{name:'Préparer ma première expédition'}).waitFor();await f.page.goto(`${base}/colis`);await f.page.getByLabel('Rechercher une expédition').fill('EXP-HISTORY');await f.page.getByRole('button').filter({hasText:'EXP-HISTORY'}).waitFor();assert.equal(await f.page.getByText('Aucune expédition ne correspond à cette vue.',{exact:true}).count(),0);
  await f.page.setViewportSize({width:390,height:844});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await f.page.screenshot({path:path.join(output,'history-mobile.png'),fullPage:true});
 });
 await check('archive-failure-and-retry',async f=>{
  let fail=true;await f.context.route('**/rest/v1/client_colis*',r=>new URL(r.request().url()).searchParams.get('archive')==='eq.true'&&fail?r.fulfill({status:503,contentType:'application/json',body:'{"message":"Fixture unavailable"}'}):r.fallback());
  await f.login();await f.page.goto(`${base}/colis`);await f.page.getByRole('button',{name:/^Historique/}).click();await f.page.getByRole('alert').filter({hasText:'La recherche reste incomplète'}).waitFor();assert.equal(await f.page.getByText('Aucune expédition ne correspond à cette vue.',{exact:true}).count(),0);fail=false;await f.page.getByRole('button',{name:'Réessayer le chargement de l’historique'}).click();await f.page.getByRole('status').filter({hasText:'0 expédition affichée'}).waitFor();
 });
 await check('targeted-invoice-correction',async f=>{
  f.tables.colis[0].statut='en_preparation';Object.assign(f.tables.factures[0],{valide:false,rejet_motif:'Dernière page manquante'});await f.context.route('**/storage/v1/object/factures/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));await open(f);await f.page.getByRole('button',{name:'Corriger une facture',exact:true}).click();assert.equal(await f.page.getByLabel('Facture corrigée',{exact:true}).inputValue(),ids.F);await f.page.getByRole('form',{name:'Déposer une facture'}).getByText(/Correction demandée : Dernière page/).waitFor();assert.equal(await f.page.getByLabel('Facture ou photo',{exact:true}).getAttribute('multiple'),null);
  await f.page.getByLabel('Facture ou photo',{exact:true}).setInputFiles({name:'corrected.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 synthetic')});await f.page.getByRole('button',{name:'Déposer la facture',exact:true}).click();await f.page.getByRole('status').filter({hasText:'Facture reçue et enregistrée'}).waitFor();assert.equal(f.tables.factures.length,2);assert.equal(f.tables.factures[1].replaces_facture_id,ids.F);assert.equal(f.tables.factures[0].rejet_motif,'Dernière page manquante');
 });
 await check('correction-refresh-preserves-files-and-explicit-new-deposit',async f=>{
  f.tables.colis[0].statut='en_preparation';await open(f);await f.page.getByRole('button',{name:/^Documents \(/}).click();await f.page.getByRole('form',{name:'Déposer une facture'}).waitFor();await f.page.getByRole('button',{name:/^Messages \(/}).click();
  Object.assign(f.tables.factures[0],{valide:false,rejet_motif:'Dernière page manquante'});await f.page.evaluate(()=>window.dispatchEvent(new Event('focus')));await f.page.getByRole('button',{name:'Corriger une facture',exact:true}).click();const choice=f.page.getByLabel('Facture corrigée',{exact:true});await f.page.waitForFunction(id=>document.querySelector('select[aria-label="Facture corrigée"]')?.value===id,ids.F);assert.equal(await choice.inputValue(),ids.F);
  await choice.selectOption('');const files=f.page.getByLabel('Facture ou photo',{exact:true});await files.setInputFiles({name:'nouvel-achat.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 synthetic')});f.tables.factures.push({...f.tables.factures[0],id:'94444444-4444-4444-8444-444444444444',vendeur:'Autre boutique',rejet_motif:'Date manquante'});await f.page.evaluate(()=>window.dispatchEvent(new Event('focus')));await choice.getByRole('option',{name:'Corriger : Autre boutique'}).waitFor({state:'attached'});assert.equal(await choice.inputValue(),'');assert.equal(await files.evaluate(input=>input.files[0]?.name),'nouvel-achat.pdf');assert.equal(f.requests.filter(r=>r.path.endsWith('/factures')&&r.method==='POST').length,0);
 });
 await check('correcting-one-of-two-targets-the-remaining-invoice',async f=>{
  f.tables.colis[0].statut='en_preparation';Object.assign(f.tables.factures[0],{valide:false,rejet_motif:'Page manquante'});const other='94444444-4444-4444-8444-444444444444';f.tables.factures.push({...f.tables.factures[0],id:other,vendeur:'Autre boutique'});await f.context.route('**/storage/v1/object/factures/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));await open(f);await f.page.getByRole('button',{name:'Corriger une facture',exact:true}).click();const choice=f.page.getByLabel('Facture corrigée',{exact:true});await choice.selectOption(ids.F);await f.page.getByLabel('Facture ou photo',{exact:true}).setInputFiles({name:'correction.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 synthetic')});await f.page.getByRole('button',{name:'Déposer la facture',exact:true}).click();await f.page.getByRole('status').filter({hasText:'Facture reçue et enregistrée'}).waitFor();await f.page.waitForFunction(id=>document.querySelector('select[aria-label="Facture corrigée"]')?.value===id,other);assert.equal(await choice.inputValue(),other);assert.equal(f.tables.factures.length,3);assert.equal(f.tables.factures[2].replaces_facture_id,ids.F);
 });
 await check('profile-documents-account-and-help',async f=>{
  Object.assign(f.tables.factures[0],{valide:false,rejet_motif:'Ancienne erreur'});f.tables.factures.push({...f.tables.factures[0],id:'84444444-4444-4444-8444-444444444444',replaces_facture_id:ids.F,rejet_motif:null,valide:true});Object.assign(f.tables.clients[0],{telegram_chat_id:'fixture-only',telegram_username:'compte_fictif'});await f.login();await f.page.goto(`${base}/profil`);await f.page.getByText('Email de connexion : audit@example.test',{exact:true}).waitFor();await f.page.getByText('Mes documents',{exact:true}).click();await f.page.getByRole('button',{name:'Factures d’achat',exact:true}).click();assert.equal(await f.page.getByText(/À corriger/).count(),0);await f.page.getByText(/EXP-TEST-001 · Validée/).waitFor();await f.page.getByText('Anciennes versions et copies',{exact:true}).click();await f.page.getByText(/EXP-TEST-001 · Remplacée/).waitFor();await f.page.getByText(/@compte_fictif est connecté/).waitFor();await f.page.getByRole('link',{name:'Demander le changement de compte Telegram'}).waitFor();await f.page.getByRole('button',{name:'Revoir le guide de démarrage'}).click();await f.page.getByRole('dialog').waitFor();await f.page.getByRole('link',{name:'Demander les consignes de réception'}).waitFor();await f.page.getByRole('button',{name:'Voir l’étape 2'}).click();await f.page.getByText(/Attendre d’autres achats/).waitFor();
 });
 await check('multiple-corrections-require-choice-and-telegram-link-can-renew',async f=>{
  f.tables.colis[0].statut='en_preparation';Object.assign(f.tables.factures[0],{valide:false,rejet_motif:'Page manquante'});f.tables.factures.push({...f.tables.factures[0],id:'94444444-4444-4444-8444-444444444444',vendeur:'Boutique B'});
  await open(f);await f.page.getByRole('button',{name:'Corriger une facture',exact:true}).click();assert.equal(await f.page.getByLabel('Facture corrigée',{exact:true}).inputValue(),'choose');assert.equal(await f.page.getByRole('button',{name:'Déposer la facture',exact:true}).isEnabled(),false);await f.page.getByLabel('Facture corrigée',{exact:true}).selectOption('94444444-4444-4444-8444-444444444444');assert.equal(await f.page.getByLabel('Facture ou photo',{exact:true}).getAttribute('multiple'),null);
  let invitations=0;await f.context.route('**/rest/v1/rpc/create_telegram_invitation',r=>{invitations++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({url:`https://t.me/fictitious_bot?start=fixture${invitations}`})});});await f.page.goto(`${base}/profil`);await f.page.getByRole('button',{name:'Connecter mon Telegram',exact:true}).click();await f.page.getByRole('link',{name:'Connecter Telegram',exact:true}).waitFor();await f.page.getByText(/Le compte n’est connecté qu’après cette confirmation/).waitFor();await f.page.getByRole('button',{name:'Lien expiré ? Créer un nouveau lien',exact:true}).click();await f.page.waitForFunction(()=>document.querySelector('a[href*="fixture2"]'));assert.equal(invitations,2);assert.equal(f.requests.some(r=>r.path.endsWith('/factures')&&r.method==='POST'),false);
 });
 await check('notification-target-and-persistent-message',async f=>{
  f.tables.notifications[0].type='message';f.tables.notifications[0].titre='Nouvelle réponse';f.tables.colis[0].conversation_statut='attente_client';await f.login();await f.page.goto(`${base}/notifications`);await f.page.getByRole('button',{name:/Nouvelle réponse/}).click();const input=f.page.getByLabel('Votre message à l’équipe',{exact:true});await input.waitFor();assert.equal(new URL(f.page.url()).searchParams.get('panel'),'messages');await input.fill('Adresse complète\nBâtiment B');await input.press('Enter');await input.type('Étage 2');const value=await input.inputValue();assert.match(value,/\nÉtage 2/);await f.page.getByRole('button',{name:'Retour à mes colis'}).click();await f.page.getByRole('button').filter({hasText:'EXP-TEST-001'}).click();await f.page.getByRole('button',{name:/^Messages \(/}).click();assert.equal(await input.inputValue(),value);assert.equal(f.requests.filter(r=>r.path.endsWith('/messages')&&r.method==='POST').length,0);await f.page.reload();await input.waitFor();assert.equal(await input.inputValue(),value);
 });
 await check('wait-reason-and-outgoing-versus-supplier-tracking',async f=>{
  Object.assign(f.tables.colis[0],{attente_client_date:'2026-09-12T08:00:00Z',attente_client_motif:'Encore un achat à recevoir',attente_client_until:'2026-09-20'});await open(f);await f.page.getByText('Encore un achat à recevoir',{exact:true}).first().waitFor();const active=f.page.getByRole('region',{name:'État actuel et prochaine étape'});assert.match(await active.innerText(),/Réexamen prévu/);Object.assign(f.tables.colis[0],{statut:'transit',envoi_id:'depart-test',attente_client_date:null,trackings:['FOURNISSEUR-A','FOURNISSEUR-B'],paiement_date:'2026-09-16T08:00:00Z'});f.tables.envois=[{id:'depart-test',tracking_principal:'TRANSPORT-SORTANT',statut:'parti'}];await f.page.reload();await f.page.getByText('Suivi et détails de l’expédition',{exact:true}).click();const out=f.page.getByRole('link',{name:/Suivi vers votre adresse/});await out.waitFor();assert.match(await out.getAttribute('href'),/TRANSPORT-SORTANT$/);await f.page.getByText('Suivis fournisseurs vers l’entrepôt',{exact:true}).click();assert.match(await f.page.getByRole('link',{name:'FOURNISSEUR-B',exact:true}).getAttribute('href'),/FOURNISSEUR-B$/);assert.match(await active.innerText(),/Dernier événement logistique renseigné : réception/);
 });
 await check('payment-first-and-mobile-accessibility',async f=>{
  Object.assign(f.tables.colis[0],{statut:'devis_envoye',devis_total:88,devis_transport:88,devis_brouillon:false,devis_envoye_le:'2026-09-16T08:00:00Z',mode_paiement_pro:'virement'});f.tables.clients[0].type='pro';await open(f);await f.page.getByText('Montant à régler',{exact:true}).waitFor();assert.equal(await f.page.getByText('Transport optimisé',{exact:true}).isVisible(),false);await f.page.getByText(/Utilisez les coordonnées bancaires transmises/).waitFor();await f.page.getByText('Détail du devis',{exact:true}).click();await f.page.getByText('Transport optimisé',{exact:true}).waitFor();await f.page.setViewportSize({width:390,height:844});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const axe=await new AxeBuilder({page:f.page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();assert.deepEqual(axe.violations.map(v=>v.id),[]);await f.page.screenshot({path:path.join(output,'payment-mobile.png'),fullPage:true});
 });
 await check('public-neutral-status-and-retry',async f=>{
  let status=503;await f.context.route('**/functions/v1/get-tracking?*',r=>status===200?r.fallback():r.fulfill({status,contentType:'application/json',body:'{"ok":false,"error":"fixture"}'}));await f.page.goto(`${base}/suivi/fixture-token`);await f.page.getByRole('button',{name:'Réessayer le suivi'}).waitFor();assert.equal(await f.page.getByText(/obtenir un nouveau lien/).count(),0);status=200;await f.page.getByRole('button',{name:'Réessayer le suivi'}).click();await f.page.getByRole('heading',{name:'Règlement attendu du client'}).waitFor();assert.doesNotMatch(await f.page.locator('body').innerText(),/À vous|Consulter le devis et ses modalités/);status=410;await f.page.reload();await f.page.getByText(/obtenir un nouveau lien/).waitFor();assert.equal(await f.page.getByRole('button',{name:'Réessayer le suivi'}).count(),0);
 });
 }finally{await browser.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));}
})().catch(e=>{console.error(e);process.exitCode=1;});
