/* Isolated integration tests: mock all external requests, exercise real routes/components. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const AxeBuilder = require('@axe-core/playwright').default;
const { setup, ids, base } = require('./browser-regression.cjs');
const { A, C, P, S } = ids;
const B = '88888888-1111-4111-8111-111111111111';
const P2 = '99999999-1111-4111-8111-111111111111';
const output = process.env.PINTA_WORKSPACE_OUT || path.resolve(__dirname, '../../docs/verification-organisation-2026-09-12');
const results = [];
(async () => {
 await fs.mkdir(output, { recursive: true });
 const browser = await chromium.launch({ headless: true });
 let f;
 try {
  f = await setup(browser, 'directeur');
  f.tables.clients[0].user_id = C;
  f.tables.staff_users.push({ id: B, auth_id: B, nom: 'Alex', prenom: 'Alex', role: 'directeur', actif: true, staff_permissions: {} });
  f.tables.staff_work_preferences = [{ staff_id: A, missions: ['reception','preparation','communication','documents','departures','coordination'], available: true, density: 'comfortable', active_mission: null, version: 1 }];
  f.tables.colis[0].conversation_statut = 'a_traiter'; f.tables.colis[0].conversation_version = 1;
  f.tables.colis.push({ ...f.tables.colis[0], id: P2, ref: 'EXP-TEST-002', conversation_statut: 'a_traiter' });
  const created = new Date().toISOString();
  const mk = (id, kind, changes = {}) => ({ id, colis_id: P, kind, state: 'ready', assignee_id: A, version: 1, created_at: created, updated_at: created, ...changes });
  f.tables.staff_work_actions = [mk('prepare','preparation'), mk('quote','quote',{ due_at: '2020-01-01T10:00:00Z' }), mk('conversation','conversation',{ assignee_id: null }), mk('documents','documents',{ state: 'waiting', waiting_reason: 'Vérification fournisseur', review_at: '2099-01-01' }), mk('departure','departure',{ state: 'in_progress' })];
  f.tables.messages = [{ id: 'm1', colis_id: P, type: 'client', texte: 'Pouvez-vous vérifier le premier carton ?', auteur_nom: 'Camille', canal: 'portal', lu: false, created_at: created }, { id: 'm2', colis_id: P2, type: 'client', texte: 'Question sur le second dossier', auteur_nom: 'Camille', canal: 'portal', lu: false, created_at: created }];
  f.tables.messages.unshift({ id: 'attachment-message', colis_id: P, type: 'client', texte: 'Photo du contenu à vérifier', auteur_nom: 'Camille', canal: 'telegram', lu: true, created_at: created, attachment_path: P + '/photo.pdf', attachment_name: 'document-client.pdf', attachment_type: 'application/pdf' });
  f.tables.client_inbox = [{ id: 'inbox-1', client_id: C, status: 'unassigned', texte: 'À quel dossier rattacher cette question ?', created_at: created }];
  let failPreferences = false;
  await f.context.route('**/functions/v1/telegram-inbox-assign', async route => {
   const input = route.request().postDataJSON(); const item = f.tables.client_inbox.find(row => row.id === input.inboxId);
   item.status = 'assigned'; item.assigned_colis_id = input.colisId;
   f.tables.messages.push({ id: 'assigned-message', colis_id: input.colisId, type: 'client', texte: item.texte, lu: false, created_at: created });
   return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true }) });
  });
  await f.context.route('**/rest/v1/rpc/*', async route => {
   const name = new URL(route.request().url()).pathname.split('/').pop(); const input = route.request().postDataJSON();
   let body, status = 200;
   if (name === 'mutate_staff_work_action') {
    const action = f.tables.staff_work_actions.find(item => item.id === input.p_action_id);
    if (action.version !== input.p_expected_version) { status = 409; body = { code: '40001', message: 'Cette action a changé. Un collègue la suit déjà.' }; }
    else {
     const command = input.p_command; const payload = input.p_payload || {};
     if (command === 'claim') action.assignee_id = A;
     if (command === 'start') action.state = 'in_progress';
     if (command === 'handoff') { action.handoff_to = payload.staff_id; action.handoff_note = payload.note; }
     if (command === 'wait') { action.state = 'waiting'; action.waiting_reason = payload.reason; action.review_at = payload.review_at; }
     action.version++; body = action;
    }
   } else if (name === 'import_conversation_invoice') {
    const message = f.tables.messages.find(item => item.id === input.p_message_id);
    body = { id: 'imported-facture', colis_id: message.colis_id, vendeur: 'Document à vérifier', montant: 0, valide: false, fichier_url: message.attachment_path };
    f.tables.factures.push(body);
   } else if (name === 'set_conversation_state') {
    const parcel = f.tables.colis.find(item => item.id === input.p_colis_id); parcel.conversation_statut = input.p_state; parcel.conversation_version++; body = parcel;
   } else if (name === 'save_staff_work_preferences') {
    if (failPreferences) return route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: '40001', message: 'Préférences modifiées dans une autre session.' }) });
    const pref = f.tables.staff_work_preferences.find(item => item.staff_id === A); Object.assign(pref, input.p_preferences); pref.version++; body = pref;
   } else return route.fallback();
   return route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) });
  });
  await f.login();
  await f.page.getByRole('heading', { name: 'Mon travail', exact: true }).waitFor();
  await f.page.getByRole('button', { name: 'À faire 3', exact: true }).waitFor();
  assert.equal(await f.page.getByRole('navigation', { name: 'Mes actions', exact: true }).getByRole('button').count(), 2);
  await f.page.getByRole('region', { name: 'À faire', exact: true }).getByText('En cours', { exact: true }).waitFor();
  await f.page.getByRole('button', { name: 'À prendre 1', exact: true }).waitFor();
  await f.page.getByRole('button', { name: 'En attente 1', exact: true }).waitFor();
  assert.equal(await f.page.locator('section[aria-label="À faire"] article h2').first().innerText(), 'Établir le devis');
  await f.page.screenshot({ path: path.join(output, 'personal-desktop.png'), fullPage: true });
  await f.page.getByLabel('Mission', { exact: true }).selectOption('preparation');
  await f.page.getByRole('button', { name: 'À faire 1', exact: true }).waitFor();
  await f.page.getByRole('link', { name: 'Traiter le suivant', exact: true }).click();
  await f.page.waitForURL('**/colis/' + P + '?*');
  assert.equal(new URL(f.page.url()).searchParams.get('returnTo'), '/?mission=preparation');
  results.push({ test: 'personal-permitted-mission-counts-and-exact-next-route', pass: true });
  await f.page.goto(base + '/equipe?mission=preparation');
  const prepare = f.page.locator('article').filter({ hasText: 'Préparer les cartons' });
  await prepare.getByRole('button', { name: 'Suivi', exact: true }).click();
  await prepare.getByRole('button', { name: 'Passer le relais', exact: true }).click();
  await prepare.getByLabel('Proposer le relais à').selectOption(B);
  await prepare.getByLabel('Consigne pour la reprise').fill('Vérifier la protection du carton 2.');
  await prepare.getByRole('button', { name: 'Confirmer', exact: true }).click();
  await prepare.getByText(/Relais proposé à Alex/).waitFor();
  assert.equal(f.tables.staff_work_actions[0].assignee_id, A);
  assert.equal(f.tables.staff_work_actions[0].handoff_to, B);
  results.push({ test: 'handoff-retains-owner-until-acceptance', pass: true });
  await f.page.screenshot({ path: path.join(output, 'team-desktop.png'), fullPage: true });
  await f.page.goto(base + '/conversations?dossier=' + P);
  await f.page.getByRole('link', { name: 'document-client.pdf', exact: true }).waitFor();
  assert.equal(f.tables.factures.length, 1, 'Receiving a conversation document does not automatically create an invoice');
  await f.page.getByRole('button', { name: 'Utiliser comme facture', exact: true }).click();
  await f.page.getByText('Facture ajoutée, à vérifier dans Documents.', { exact: true }).waitFor();
  assert.equal(f.tables.factures.length, 2);
  assert.equal(f.tables.factures[1].valide, false);
  results.push({ test: 'private-conversation-attachment-is-explicitly-imported-as-unvalidated-invoice', pass: true });
  await f.page.locator('#staff-message-' + P).fill('Brouillon dossier 1');
  await f.page.getByRole('button').filter({ hasText: 'Question sur le second dossier' }).click();
  await f.page.locator('#staff-message-' + P2).fill('Brouillon dossier 2');
  await f.page.getByRole('button').filter({ hasText: 'Pouvez-vous vérifier le premier carton' }).click();
  assert.equal(await f.page.locator('#staff-message-' + P).inputValue(), 'Brouillon dossier 1');
  assert.equal(f.tables.colis[0].conversation_statut, 'a_traiter');
  await f.page.getByRole('button', { name: 'Je m’en occupe', exact: true }).click();
  await f.page.getByRole('button', { name: 'Commencer', exact: true }).waitFor();
  assert.equal(f.tables.staff_work_actions.find(item => item.id === 'conversation').assignee_id, A);
  await f.page.screenshot({ path: path.join(output, 'conversations-desktop.png'), fullPage: true });
  assert.equal(await f.page.getByRole('dialog').count(), 0);
  assert.ok(await f.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  results.push({ test: 'conversations-dossier-drafts-read-not-resolved-and-explicit-claim', pass: true });
  await f.page.setViewportSize({ width: 390, height: 844 });
  await f.page.getByRole('button', { name: 'Voir le dossier', exact: true }).click();
  await f.page.getByRole('heading', { name: /Mesures à réception/ }).filter({ visible: true }).waitFor();
  await f.page.getByRole('button', { name: 'Revenir aux messages', exact: true }).click();
  assert.equal(await f.page.locator('#staff-message-' + P).inputValue(), 'Brouillon dossier 1');
  assert.ok(await f.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  const composer = await f.page.getByRole('button', { name: 'Envoyer le message', exact: true }).boundingBox();
  assert.ok(composer && composer.y + composer.height <= 780, 'The composer remains above mobile navigation');
  const accessibility = await new AxeBuilder({ page: f.page }).analyze();
  const failures = accessibility.violations.filter(item => ['critical','serious'].includes(item.impact));
  assert.deepEqual(failures.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), []);
  await f.page.screenshot({ path: path.join(output, 'conversations-mobile.png'), fullPage: true });
  results.push({ test: 'mobile-conversation-context-preserves-draft-without-overlay', pass: true });
  await f.page.goto(base + '/colis?dossier=' + P);
  await f.page.getByRole('button', { name: 'Vérifier les factures', exact: true }).click();
  await f.page.waitForURL(url => url.pathname === '/colis/' + P && url.searchParams.get('section') === 'documents');
  assert.equal(new URL(f.page.url()).searchParams.get('returnTo'), '/colis?dossier=' + P);
  await f.page.getByRole('region', { name: 'Factures d’achat', exact: true }).waitFor();
  assert.equal(await f.page.getByRole('button', { name: 'Valider le devis', exact: true }).count(), 0);
  await f.page.goto(base + '/colis?dossier=' + P);
  await f.page.getByRole('button', { name: 'Ouvrir la conversation client', exact: true }).click();
  await f.page.waitForURL('**/conversations?*');
  assert.equal(new URL(f.page.url()).searchParams.get('returnTo'), '/colis?dossier=' + P);
  results.push({ test: 'quick-dossier-opens-current-task-and-conversation-preserving-return', pass: true });
  await f.page.locator('#staff-message-' + P).waitFor();
  const liveAction = f.tables.staff_work_actions.find(item => item.id === 'conversation');
  liveAction.version++; liveAction.assignee_id = B;
  await f.page.getByRole('button', { name: 'Commencer', exact: true }).click();
  await f.page.getByRole('alert').filter({ hasText: 'Cette action a changé' }).waitFor();
  assert.equal(liveAction.assignee_id, B);
  await f.page.getByRole('button', { name: 'Actualiser l’action', exact: true }).click();
  await f.page.getByText('Conversation : Alex Alex', { exact: true }).waitFor();
  results.push({ test: 'stale-action-conflict-keeps-colleague-owner-and-offers-refresh', pass: true });
  await f.page.goto(base + '/conversations?inbox=inbox-1');
  await f.page.getByLabel('Dossier du client').selectOption(P2);
  await f.page.getByRole('button', { name: 'Rattacher au dossier', exact: true }).click();
  await f.page.locator('#staff-message-' + P2).waitFor();
  assert.equal(f.tables.client_inbox[0].assigned_colis_id, P2);
  results.push({ test: 'unassigned-message-shares-conversation-view-and-explicit-dossier-assignment', pass: true });
  await f.page.goto(base + '/?section=pool');
  await f.page.getByRole('button', { name: 'Mes missions et disponibilité', exact: true }).click();
  await f.page.getByLabel('Disponible pour prendre de nouvelles actions').uncheck();
  await f.page.getByLabel('Absence jusqu’au (facultatif)').fill('2099-10-01T10:00');
  await f.page.getByRole('button', { name: 'Enregistrer', exact: true }).click();
  await f.page.getByText(/Indisponibilité déclarée/).waitFor();
  assert.ok(f.tables.staff_work_actions.some(item => item.assignee_id === A));
  await f.page.getByRole('button', { name: 'Mes missions et disponibilité', exact: true }).click();
  assert.equal(await f.page.getByLabel('Absence jusqu’au (facultatif)').inputValue(), '2099-10-01T10:00');
  results.push({ test: 'availability-saved-without-transferring-work-and-absence-date-preserved', pass: true });
  failPreferences = true;
  await f.page.getByLabel('Absence jusqu’au (facultatif)').fill('2099-10-02T10:00');
  await f.page.getByRole('button', { name: 'Enregistrer', exact: true }).click();
  await f.page.getByRole('alert').filter({ hasText: 'Préférences modifiées' }).waitFor();
  assert.equal(await f.page.getByLabel('Absence jusqu’au (facultatif)').inputValue(), '2099-10-02T10:00');
  results.push({ test: 'preference-conflict-is-visible-and-draft-retained', pass: true });
  f.tables.colis[0].envoi_id = 'departure-test';
  await f.page.goto(base + '/colis?envoi=departure-test');
  await f.page.getByRole('status').filter({ hasText: '1 dossier(s) affiché(s)' }).waitFor();
  assert.equal(await f.page.getByRole('button', { name: 'EXP-TEST-002', exact: true }).count(), 0);
  results.push({ test: 'departure-url-filter-count-and-rows-share-scope', pass: true });
  await f.page.goto(base + '/?mission=preparation');
  const personalRow = f.page.locator('article').filter({ hasText: 'Préparer les cartons' });
  await personalRow.getByRole('button', { name: 'Suivi', exact: true }).click();
  await personalRow.getByRole('button', { name: 'Passer le relais', exact: true }).click();
  const relayDraft = personalRow.getByLabel('Consigne pour la reprise');
  await relayDraft.fill('Consigne conservée pendant actualisation.');
  await f.context.route('**/rest/v1/staff_work_actions?*', async route => { await new Promise(resolve => setTimeout(resolve, 300)); return route.fallback(); });
  const refreshed = f.page.waitForResponse(response => response.url().includes('/rest/v1/staff_work_actions?'));
  await f.page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await refreshed;
  assert.equal(await relayDraft.inputValue(), 'Consigne conservée pendant actualisation.');
  results.push({ test: 'background-focus-refresh-keeps-action-form-draft-mounted', pass: true });
  f.tables.colis.find(item => item.id === P2).conversation_statut = 'termine';
  await f.page.goto(base + '/conversations?dossier=' + P2);
  await f.page.locator('#staff-message-' + P2).waitFor();
  await f.page.locator('#conversation-client').getByText('Traitée', { exact: true }).waitFor();
  assert.equal(await f.page.locator('#conversation-client').getByText('Conversation : Non attribué', { exact: true }).count(), 0);
  await f.page.goto(base + '/conversations?owner=unassigned');
  assert.equal(await f.page.getByRole('button').filter({ hasText: 'EXP-TEST-002' }).count(), 0);
  results.push({ test: 'closed-conversations-without-active-action-are-treated-not-unassigned', pass: true });
  for (const width of [1440,390]) for (const dark of [false,true]) for (const [route,title] of [['/','Mon travail'],['/equipe','Équipe'],['/conversations?dossier=' + P,'Conversations']]) {
   await f.page.setViewportSize({ width, height: width === 390 ? 844 : 1000 });
   await f.page.goto(base + route);
   await f.page.getByRole('heading', { name: title, exact: true }).waitFor();
   const mode = await f.page.locator('html').evaluate(element => element.classList.contains('dark'));
   if (mode !== dark) await f.page.getByRole('button', { name: dark ? 'Passer en mode sombre' : 'Passer en mode clair', exact: true }).filter({ visible: true }).click();
   const audit = await new AxeBuilder({ page: f.page }).analyze();
   const serious = audit.violations.filter(item => ['critical','serious'].includes(item.impact));
   assert.deepEqual(serious.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], `${title}, ${width}px, dark=${dark}`);
   assert.ok(await f.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${title} fits viewport`);
   if (dark) await f.page.screenshot({ path: path.join(output, `workspace-${title === 'Mon travail' ? 'personal' : title === 'Équipe' ? 'team' : 'conversations'}-${width}-dark.png`), fullPage: true });
   results.push({ test: `axe-${title}-${width}-${dark ? 'dark' : 'light'}`, pass: true });
  }
  assert.equal(f.errors.length, 0, f.errors.join('\n')); assert.equal(f.networkDenied.length, 0, f.networkDenied.join('\n'));
  await f.context.close();
  f = await setup(browser, 'directeur', { failTable: 'staff_work_actions' });
  await f.login();
  await f.page.getByRole('alert').filter({ hasText: 'Indisponibilité simulée' }).waitFor();
  await f.page.getByRole('button', { name: 'Réessayer', exact: true }).waitFor();
  results.push({ test: 'work-loading-failure-visible-with-retry', pass: true });
 } catch (error) {
  results.push({ test: 'failure', message: error.stack }); process.exitCode = 1;
  await f?.page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }).catch(() => {});
 } finally {
  await browser.close(); if (!process.exitCode) await fs.rm(path.join(output, 'failure.png'), { force: true }); await fs.writeFile(path.join(output, 'workspace-browser.json'), JSON.stringify(results, null, 2)); console.log(JSON.stringify(results, null, 2));
 }
})();
