/* Uses the existing isolated fixture transport; no production/provider request is allowed. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { setup, base, ids: { P } } = require('./browser-regression.cjs');
const { fixture: invoiceFixture } = require('./invoice-workspace.cjs');
const { chromium } = require(process.env.PINTA_PLAYWRIGHT_MODULE || 'playwright');
const output = process.env.PINTA_UX_DEVIS_OUT || path.resolve(__dirname, '../../docs/verification-ux-devis-client-2026-09-10');
async function main() {
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ headless: true });
  const results = [];
  let current;
  try {
    current = await setup(browser, 'client');
    current.tables.colis[0].nb_colis = 3;
    current.tables.colis[0].trackings = ['TEST-001'];
    current.tables.colis[0].trackings_detail = [{ number: 'TEST-001' }];
    await current.login();
    await current.page.goto(`${base}/colis/${P}`);
    await current.page.getByRole('button', { name: 'Autoriser la préparation', exact: true }).click();
    await current.page.getByRole('dialog').waitFor();
    assert.match(await current.page.getByRole('dialog').innerText(), /3 carton\(s\)/);
    assert.match(await current.page.getByRole('dialog').innerText(), /EXP-TEST-001/);
    await current.page.getByRole('button', { name: 'Annuler', exact: true }).click();
    await current.page.setViewportSize({ width: 390, height: 844 });
    await current.page.goto(`${base}/colis/${P}`);
    const authorize = current.page.getByRole('button', { name: 'Autoriser la préparation', exact: true });
    await authorize.waitFor();
    const box = await authorize.boundingBox();
    results.push({ test: 'client-scoped-consent-three-cartons-one-tracking', pass: true, authorizeBox: box });
    await current.page.waitForTimeout(400);
    await current.page.screenshot({ path: path.join(output, 'client-decision-mobile.png') });
    await current.page.getByRole('button', { name: 'Attendre d’autres achats', exact: true }).click();
    await current.page.getByLabel('Votre précision').fill('Dernier achat attendu');
    await current.page.getByRole('button', { name: 'Enregistrer mon attente' }).click();
    await current.page.getByRole('heading', { name: 'En attente à votre demande' }).waitFor();
    assert.equal(current.tables.colis[0].attente_client_motif, 'Dernier achat attendu');
    assert.equal(current.errors.length, 0, current.errors.join('\n'));
    results.push({ test: 'client-deliberate-wait-saved', pass: true });
    let uploads = 0;
    await current.context.route('**/storage/v1/object/factures/**', async (route) => { uploads++; await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ Key: new URL(route.request().url()).pathname }) }); });
    await current.page.getByRole('button', { name: /^Documents \(/ }).click();
    const upload = current.page.getByLabel('Facture ou photo', { exact: true });
    await upload.setInputFiles({ name: 'achat.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 fixture') });
    await current.page.getByRole('button', { name: 'Déposer la facture', exact: true }).click();
    await current.page.getByText('Facture reçue et enregistrée.', { exact: false }).waitFor();
    assert.equal(current.tables.factures.length, 2);
    assert.equal(current.tables.factures[1].valide, false);
    assert.equal(current.tables.factures[1].montant, 0);
    assert.ok(current.tables.factures[1].fichier_url.startsWith(P + '/'));
    let rejectInsert = true;
    await current.context.route('**/rest/v1/factures*', async (route) => { if (route.request().method() === 'POST' && rejectInsert) { rejectInsert = false; await route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ message: 'Insertion indisponible pour test' }) }); } else await route.fallback(); });
    await upload.setInputFiles({ name: 'correction.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 correction') });
    await current.page.getByRole('button', { name: 'Déposer la facture', exact: true }).click();
    await current.page.getByRole('alert').filter({ hasText: 'Insertion indisponible pour test' }).waitFor();
    assert.equal(current.tables.factures.length, 2);
    await current.page.getByRole('button', { name: 'Réessayer les documents en échec', exact: true }).click();
    await current.page.getByText('Facture reçue et enregistrée.', { exact: false }).waitFor();
    assert.equal(current.tables.factures.length, 3); assert.equal(uploads, 2);
    assert.equal(current.errors.length, 0, current.errors.join('\n'));
    results.push({ test: 'client-document-private-deposit-and-failed-insert-retry-no-duplicate-upload', pass: true });
    await current.context.close();

    current = await invoiceFixture(browser);
    const ocrCalls = [];
    await current.context.route('**/functions/v1/ocr-facture', async (route) => {
      const body = route.request().postDataJSON(); ocrCalls.push(body);
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, extraction: { id: '77777777-7777-4777-8777-777777777777', status: 'review', vendeur: 'Boutique A', total: 100, lines: [{ desc: 'Article à relire', qte: 1, prix: 100, cat: null }], warnings: ['Catégorie à confirmer'] } }) });
    });
    await current.login();
    await current.page.setViewportSize({ width: 390, height: 844 });
    await current.page.goto(`${base}/colis/${P}?section=documents`);
    await current.page.getByText('Propositions de l’analyse : vérifiez les articles et leurs catégories.', { exact: true }).waitFor();
    assert.ok(current.calls.some((call) => call.kind === 'context'), 'Existing review is restored through the shared context RPC');
    assert.ok(!ocrCalls.some((call) => call.action === 'extract'));
    const validation = current.page.getByRole('button', { name: 'Valider et passer à la suivante', exact: true });
    await validation.scrollIntoViewIfNeeded();
    const barBox = await validation.boundingBox();
    assert.equal(await current.page.getByTestId('quote-action-bar').count(), 0);
    results.push({ test: 'staff-invoice-validation-reachable-mobile', pass: barBox.y >= 0 && barBox.y + barBox.height <= 845, barBox });
    await current.page.screenshot({ path: path.join(output, 'staff-preparation-mobile.png') });
    await current.page.getByLabel('Description de l’article 1').fill('Correction conservée');
    await current.page.getByRole('tab', { name: 'Voir la facture', exact: true }).click();
    await current.page.getByRole('tab', { name: 'Vérifier les articles', exact: true }).click();
    assert.equal(await current.page.getByLabel('Description de l’article 1').inputValue(), 'Correction conservée');
    await current.page.getByRole('button', { name: 'Valider et passer à la suivante', exact: true }).click();
    assert.equal(current.calls.filter(call => call.kind === 'save').length, 0);
    await current.page.getByLabel('Catégorie de l’article 1').selectOption('cat-test');
    assert.equal(await current.page.getByRole('button', { name: 'Valider et passer à la suivante', exact: true }).isEnabled(), true);
    await current.page.getByLabel('Total HT de la facture').fill('150');
    await current.page.getByRole('button', { name: 'Valider et passer à la suivante', exact: true }).click();
    assert.equal(current.calls.filter(call => call.kind === 'save').length, 0);
    results.push({ test: 'ocr-resume-tabs-preserve-correction-and-block-inconsistent-total', pass: true });
    await current.page.setViewportSize({ width: 1440, height: 1000 });
    await current.page.screenshot({ path: path.join(output, 'staff-workspace-desktop.png'), fullPage: true });
    assert.equal(await current.page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal(current.errors.length, 0, current.errors.join('\n'));
    await current.context.close();
    current = await setup(browser, 'client');
    await current.page.setViewportSize({ width: 390, height: 844 });
    await current.page.goto(`${base}/suivi/fixture-tracking-token-123456789`);
    await current.page.getByText('Suivi partagé', { exact: true }).first().waitFor();
    await current.page.getByText('Parcours du colis').click();
    assert.equal(await current.page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.doesNotMatch(await current.page.locator('body').innerText(), /\d+%|aujourd'hui/);
    await current.page.screenshot({ path: path.join(output, 'tracking-mobile.png'), fullPage: true });
    results.push({ test: 'public-tracking-wraps-mobile-and-has-no-false-percentage', pass: true });
    assert.ok(results.every((result) => result.pass), JSON.stringify(results));
  } catch (error) {
    if (current) await current.page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }).catch(() => {});
    results.push({ test: 'failure', pass: false, error: error.stack });
    process.exitCode = 1;
  } finally {
    await browser.close(); fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify(results, null, 2)); console.log(JSON.stringify(results, null, 2));
  }
}
main();
