-- Stop only unsent reminders generated by the historical automatic worker.
-- Explicit operator sends, completed sends and their audit history are retained.
WITH cancelled AS (
 UPDATE notification_outbox
 SET status='cancelled',last_error='Rappel automatique arrêté : l’équipe décide de l’envoi.'
 WHERE idempotency_key LIKE 'reminder:%' AND status IN ('pending','blocked')
 RETURNING message_id
)
UPDATE messages SET statut='echec' WHERE id IN (SELECT message_id FROM cancelled);
