-- These action fields were not deployed before this release; all pre-existing
-- values were generated by workflow commands. Future operator instructions
-- must survive automatic status changes and cannot become artificial deadlines.
ALTER TABLE colis ADD COLUMN next_action_source text NOT NULL DEFAULT 'system'
 CHECK(next_action_source IN ('system','manual'));

CREATE FUNCTION guard_next_action_origin() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF current_user NOT IN ('postgres','supabase_admin') AND auth.role()<>'service_role' THEN
  IF TG_OP='INSERT' THEN
   IF NEW.next_action IS NOT NULL OR NEW.next_action_at IS NOT NULL OR NEW.next_action_source<>'system' THEN RAISE EXCEPTION 'Utilisez la commande de suivi du dossier'; END IF;
  ELSIF (NEW.next_action,NEW.next_action_at,NEW.next_action_source)
    IS DISTINCT FROM (OLD.next_action,OLD.next_action_at,OLD.next_action_source)
   THEN RAISE EXCEPTION 'Utilisez la commande de suivi du dossier';
  END IF;
 END IF;
 IF TG_OP='UPDATE' THEN
  IF OLD.next_action_source='manual' AND NEW.next_action_source='system'
   AND (OLD.next_action IS NOT NULL OR OLD.next_action_at IS NOT NULL) THEN
   -- Automation cannot erase or replace an explicit staff instruction.
   NEW.next_action:=OLD.next_action;NEW.next_action_at:=OLD.next_action_at;NEW.next_action_source:='manual';
  ELSIF OLD.next_action_source='system' AND NEW.next_action_source='system'
   AND NEW.statut IS DISTINCT FROM OLD.statut
   AND (NEW.next_action,NEW.next_action_at) IS NOT DISTINCT FROM (OLD.next_action,OLD.next_action_at) THEN
   NEW.next_action:=NULL;NEW.next_action_at:=NULL;
  END IF;
 END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER guard_next_action_origin BEFORE INSERT OR UPDATE ON colis FOR EACH ROW EXECUTE FUNCTION guard_next_action_origin();

DROP FUNCTION assign_colis_work(uuid,uuid,text,timestamptz,timestamptz);
CREATE FUNCTION assign_colis_work(p_colis_id uuid,p_responsible_staff_id uuid,p_next_action text,p_next_action_at timestamptz,p_expected_updated_at timestamptz,p_action_changed boolean DEFAULT true) RETURNS colis LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c colis;
BEGIN
 IF NOT is_staff() THEN RAISE EXCEPTION 'Accès équipe requis'; END IF;
 IF length(coalesce(p_next_action,''))>250 THEN RAISE EXCEPTION 'L’action est limitée à 250 caractères'; END IF;
 SELECT * INTO c FROM colis WHERE id=p_colis_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Dossier introuvable'; END IF;
 IF p_expected_updated_at IS NULL OR p_expected_updated_at<>c.updated_at THEN RAISE EXCEPTION 'Le suivi a changé. Rechargez le dossier.'; END IF;
 UPDATE colis SET responsible_staff_id=p_responsible_staff_id,
  next_action=CASE WHEN p_action_changed THEN nullif(trim(p_next_action),'') ELSE next_action END,
  next_action_at=CASE WHEN p_action_changed THEN p_next_action_at ELSE next_action_at END,
  next_action_source=CASE WHEN p_action_changed THEN 'manual' ELSE next_action_source END
 WHERE id=c.id RETURNING * INTO c;
 INSERT INTO audit_actions(colis_id,user_id,user_nom,action,detail) VALUES(c.id,auth.uid(),(SELECT nom FROM profiles WHERE id=auth.uid()),'work_assignment',coalesce(c.next_action,'Suivi du dossier')||CASE WHEN p_responsible_staff_id IS NULL THEN ' · non attribué' ELSE ' · responsable mis à jour' END);
 RETURN c;
END; $$;
REVOKE ALL ON FUNCTION assign_colis_work(uuid,uuid,text,timestamptz,timestamptz,boolean) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION assign_colis_work(uuid,uuid,text,timestamptz,timestamptz,boolean) TO authenticated;

CREATE OR REPLACE FUNCTION _apply_client_decision(p_colis_id uuid,p_action text,p_expected_updated_at timestamptz,p_wait_until timestamptz,p_reason text,p_actor text) RETURNS colis LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c colis; dest text; departure uuid; paris timestamp:=now() AT TIME ZONE 'Europe/Paris'; minimum_depart date;
BEGIN
 IF p_action NOT IN ('approve','wait','refuse') THEN RAISE EXCEPTION 'Décision invalide'; END IF;
 SELECT * INTO c FROM colis WHERE id=p_colis_id FOR UPDATE;
 IF NOT FOUND OR c.statut<>'attente_feu_vert' THEN RAISE EXCEPTION 'Cette demande ne peut plus être modifiée'; END IF;
 IF p_expected_updated_at IS NOT NULL AND c.updated_at<>p_expected_updated_at THEN RAISE EXCEPTION 'Le dossier a changé. Rechargez avant de confirmer.'; END IF;
 IF p_wait_until IS NOT NULL AND p_wait_until<=now() THEN RAISE EXCEPTION 'La date de reprise doit être future'; END IF;
 IF p_action='approve' THEN
  SELECT left(cp,3) INTO dest FROM clients WHERE id=c.client_id;
  minimum_depart:=date_trunc('week',paris)::date+4;
  IF extract(isodow FROM paris)>3 OR (extract(isodow FROM paris)=3 AND paris::time>=time '17:00') THEN minimum_depart:=minimum_depart+7; END IF;
  SELECT id INTO departure FROM envois WHERE destination_code=dest AND statut IN ('planifie','prochain') AND date_depart>=minimum_depart ORDER BY date_depart,id LIMIT 1;
  UPDATE colis SET statut='autorise',feu_vert='autorise',feu_vert_date=now(),attente_client_motif=NULL,attente_client_date=NULL,attente_client_until=NULL,envoi_id=coalesce(envoi_id,departure),next_action_source='system',next_action='Préparer le colis',next_action_at=NULL WHERE id=c.id RETURNING * INTO c;
 ELSIF p_action='wait' THEN
  UPDATE colis SET attente_client_motif=coalesce(nullif(trim(p_reason),''),'Attend d’autres colis'),attente_client_date=now(),attente_client_until=p_wait_until,next_action_source='system',next_action='Attente volontaire du client',next_action_at=p_wait_until WHERE id=c.id RETURNING * INTO c;
  UPDATE notification_outbox SET status='cancelled' WHERE colis_id=c.id AND status IN ('pending','blocked') AND message_id IN (SELECT id FROM messages WHERE template='relance_feu_vert');
 ELSE
  UPDATE colis SET statut='refuse_client',feu_vert='refuse',feu_vert_date=now(),attente_client_motif=NULL,attente_client_date=NULL,attente_client_until=NULL,next_action_source='system',next_action='Contacter le client pour la suite',next_action_at=NULL WHERE id=c.id RETURNING * INTO c;
 END IF;
 INSERT INTO messages(colis_id,type,auteur_id,auteur_nom,texte,canal,template) VALUES(c.id,'client',auth.uid(),p_actor,CASE p_action WHEN 'approve' THEN 'Accord de préparation enregistré pour ce dossier et ses cartons actuels.' WHEN 'wait' THEN 'Attente volontaire enregistrée. Les relances sont suspendues.' ELSE 'Préparation refusée. Notre équipe vous recontactera.' END,'portal','client_decision_'||p_action);
 INSERT INTO audit_actions(colis_id,user_id,user_nom,action,detail) VALUES(c.id,auth.uid(),p_actor,'client_decision',p_action);
 SELECT * INTO c FROM colis WHERE id=c.id;
 RETURN c;
END; $$;

CREATE OR REPLACE FUNCTION resume_wait_on_receipt() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE target colis; cl clients;
BEGIN
 IF TG_OP='UPDATE' AND (NEW.trackings,NEW.nb_colis,NEW.trackings_detail) IS NOT DISTINCT FROM (OLD.trackings,OLD.nb_colis,OLD.trackings_detail) THEN RETURN NEW; END IF;
 SELECT * INTO cl FROM clients WHERE id=NEW.client_id;
 FOR target IN SELECT * FROM colis WHERE client_id=NEW.client_id AND statut='attente_feu_vert' AND attente_client_date IS NOT NULL LOOP
  UPDATE colis SET attente_client_motif=NULL,attente_client_date=NULL,attente_client_until=NULL,demande_feu_vert_envoyee_at=NULL,next_action_source='system',next_action='Nouveau carton : renouveler la demande de préparation',next_action_at=NULL WHERE id=target.id;
  IF cl.user_id IS NOT NULL THEN INSERT INTO notifications(user_id,titre,msg,colis_id,type) VALUES(cl.user_id,'Un nouveau carton est arrivé','Vous pouvez vérifier les cartons et choisir de préparer ou continuer à attendre.',target.id,'feu_vert'); END IF;
 END LOOP;
 RETURN NEW;
END; $$;
